name: Build Scripts Data

on:
  push:
    paths:
      - "scripts/**"
      - "scripts.json"

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5


    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 24


    - name: Build scripts-data.json
      run: node build-scripts.js


    - name: Commit generated file
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git add scripts-data.json

        git commit -m "Update scripts-data.json" || exit 0

        git push
